Repository bounswe/2021SpringGroup7, pull requests merged in 2021-05, with the labels that each got.

#101 Added the practice-app folder
  practice-app/placeholder.txt
Labels: Priority: Medium, Status: Ready for Review, Type: Enhancement

#124 CB-6
  practice-app/app.py
  practice-app/follow/follow.py
  practice-app/test/test_follow.py
Labels: Backend, Type: Enhancement

#132 Cb 7
  .gitignore
  practice-app/app.py
  practice-app/home/home.py
  practice-app/requiremenets.txt
  practice-app/requirements.txt
  practice-app/savePost/savePost.py
  practice-app/test/test_home.py
  practice-app/test/test_savePost.py
Labels: Backend, Priority: High, Status: In Progress

#127 Cb 4
  practice-app/app.py
  practice-app/requirements.txt
  practice-app/search/search.py
  practice-app/test.txt
  practice-app/test/test_search.py
Labels: Backend, Priority: High

#126 Cb 8
  .gitignore
  practice-app/app.py
  practice-app/comment/comment.py
  practice-app/test/test_comment.py
Labels: Backend, Type: Enhancement

#131 Cb 9
  practice-app/app.py
  practice-app/report/reportedUser.py
  practice-app/test/test_reportedUser.py
Labels: Backend, Priority: High, Type: Enhancement

#129 Cb 10
  practice-app/app.py
  practice-app/multiMedia/multiMedia.py
  practice-app/requirements.txt
  practice-app/story/story.py
  practice-app/storyTime/storyTime.py
Labels: Backend, Priority: High

#130 CB-11
  practice-app/app.py
  practice-app/location/location.py
Labels: Backend, Priority: High

#137 Cb 2
  practice-app/api/profile/profile.py
  practice-app/app.py
Labels: Backend, Priority: Medium, Status: Waiting for Review, Type: Enhancement
